all:
	manim render -ql ranges-algo1.py RangesSort
	manim render -ql ranges-algo1.py RangesFind
	manim render -ql ranges-algo1.py RangesCount
	manim render -ql ranges-algo1.py RangesTransform
	manim render -ql ranges-algo2.py RangesCopyIf
	manim render -ql ranges-algo2.py RangesBoolPredicates
	manim render -ql ranges-algo3.py RangesMinMax
	manim render -ql ranges-algo3.py RangesReverse
	manim render -ql ranges-algo4.py RangesUnique
	manim render -ql ranges-algo4.py RangesRemoveIf
	manim render -ql ranges-algo5.py RangesFill
	manim render -ql ranges-algo5.py RangesGenerate
	manim render -ql ranges-algo6.py RangesReplaceIf
	manim render -ql ranges-algo6.py RangesPartition
	manim render -ql ranges-algo7.py RangesIsSorted
	manim render -ql ranges-algo7.py RangesBinarySearch
	manim render -ql ranges-algo8.py RangesNthElement
	manim render -ql ranges-algo8.py RangesWithStrings
	manim render -ql ranges-algo9.py RangesProjections
	manim render -ql ranges-algo10.py RangesViewsPipeline

all-hd:
	manim render -qh ranges-algo1.py RangesSort
	manim render -qh ranges-algo1.py RangesFind
	manim render -qh ranges-algo1.py RangesCount
	manim render -qh ranges-algo1.py RangesTransform
	manim render -qh ranges-algo2.py RangesCopyIf
	manim render -qh ranges-algo2.py RangesBoolPredicates
	manim render -qh ranges-algo3.py RangesMinMax
	manim render -qh ranges-algo3.py RangesReverse
	manim render -qh ranges-algo4.py RangesUnique
	manim render -qh ranges-algo4.py RangesRemoveIf
	manim render -qh ranges-algo5.py RangesFill
	manim render -qh ranges-algo5.py RangesGenerate
	manim render -qh ranges-algo6.py RangesReplaceIf
	manim render -qh ranges-algo6.py RangesPartition
	manim render -qh ranges-algo7.py RangesIsSorted
	manim render -qh ranges-algo7.py RangesBinarySearch
	manim render -qh ranges-algo8.py RangesNthElement
	manim render -qh ranges-algo8.py RangesWithStrings
	manim render -qh ranges-algo9.py RangesProjections
	manim render -qh ranges-algo10.py RangesViewsPipeline

clean:
	rm -rf media
